### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by fa-gdc** [briskat/briskat.github.io#1]
Good Afternoon sirs,
I have visited the fine page of yours and tried to navigate from demo using the link named "More information about Git Analytik". Unfortunately the following 404 error page waited for me: http://www.briskat.com/blog/Gitcharts/

Your thankfully,
fa-gdc

**Comment by vmakovsky** [comment]
Thank you very much, for reporting the first issue on our web pages.

Please accept my sincere apologies. It should be fixed now. Please just refresh the http://www.briskat.com/demo.html page.

**Comment by fa-gdc** [comment]
Nope :-( Stil 404

**Comment by vmakovsky** [comment]
I forgot to say the http://www.briskat.com/demo.html page. http://www.briskat.com/blog/Gitcharts/ no longer exists.

**Comment by fa-gdc** [comment]
Thank you, works perfectly.
