### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by lubosek** [briskat/briskat.github.io#2]
Cau, borci!
Aby mi nic neuniklo, rad bych RSS feed do ctecky. Diky za zvazeni.
Drzim palce!
LZ

**Comment by briskat** [comment]
Zvazime, ted nicmene bude nejakou dobu hlussi obdobi :-).

**Comment by briskat** [comment]
Zdare po delsi dobe. Mame novy blog post http://www.briskat.com/blog/Million_Per_Ke.
RSS zatim neplanujeme. Primarni zdroj na castejsi updaty je twitter https://twitter.com/thebriskat .
Pokud bude vyrazne vice zajemcu o RSS pak to pridame.
